name: Server
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  crypto: ^3.0.2
  mongo_dart: ^0.9.1
  uuid: ^3.0.7

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
